---
## This playbook deploys the whole application stack in this site.
#
# Configure and deploy database servers.
- hosts: {{windows_dbservers}}
  connection: winrm

  vars:
    ansible_ssh_port : 5986

  roles:
  - mssql

  tags:
  - db

# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: {{windows_webservers}}
  connection: winrm

  vars:
    ansible_ssh_port : 5986

  roles:
  - iis
  - web

  tags:
  - web

# Configure and deploy the load balancer(s).
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
   - elb

  tags:
  - lb
